Add GitHub Adapter
utopia-php/vcs pull request #1
Opened 2023-02-23 11:25 UTC by vermakhushboo

2023-06-07 06:39 UTC, Meldiron commented on tests/Detector/DetectorTest.php
> +            ->addDetector(new Ruby($files, $languages));
Feels repetitive to give files and languages to all detectors. Can we instead give it only once to factory?

2023-06-07 06:40 UTC, Meldiron commented on src/Detector/Adapter/JavaScript.php
> +    public function getEntryPoint(): string
```suggestion
    public function getEntrypoint(): string
```

2023-06-07 06:41 UTC, Meldiron commented on src/Detector/Adapter/JavaScript.php
> +        // }
I like this, why commented out?

2023-06-07 06:41 UTC, Meldiron commented on src/Detector/Adapter/Python.php
> +        // }
If we do this in all adapters, we could do it in Detector.php. In adapter we would then only setup something like `getFileExtention()`

2023-06-07 06:59 UTC, vermakhushboo commented on src/Detector/Adapter/JavaScript.php
> +        // }
Would this slow down the detection process significantly since we're looping through files in each detector?

2023-06-07 07:11 UTC, eldadfux requested changes
Great work, left a few comments, let me know if you need more guidance.

2023-06-07 07:11 UTC, eldadfux commented on src/VCS/Adapter.php
> +    protected function flatten(array $data, string $prefix = ''): array
I don't think we use this method in practice, we may be able to remove it.

2023-06-07 07:11 UTC, eldadfux commented on CONTRIBUTING.md
> +# Contributing
We should also add a step by step guide for adding a new VCS adapter and for adding a new detector. Once both are ready we should also open a few good first issues for people to be able to contribute to the repo.

2023-06-07 07:11 UTC, eldadfux commented on README.md
> +You can refer to the [Contributing Guide](CONTRIBUTING.md) for more info.
We can later link to specific contributions tutorials from here.

2023-06-07 07:11 UTC, eldadfux commented on composer.json
> +        "vlucas/phpdotenv": "^5.5",
We should probably avoid using this dependency. Where are we using it?

2023-06-07 07:11 UTC, eldadfux commented on src/Detector/DetectorFactory.php
> +    public function __construct(array $detectors = [])
The naming convention got me confused compared to existing patterns. It might work better if we call this class `Utopia\Detector\Detector` and for the other one we use `Utopia\Detector\Adapter`. It's completely fine to use the adapter pattern twice here.

2023-06-07 07:11 UTC, eldadfux commented on src/VCS/Adapter.php
> +    public function call(string $method, string $path = '', array $headers = [], array $params = [], bool $decode = true)
This method should be protected, we should only use it internally inside the adapter.

2023-06-07 10:45 UTC, vermakhushboo commented on src/VCS/Adapter.php
> +    protected function flatten(array $data, string $prefix = ''): array
```
case 'multipart/form-data':
      $query = $this->flatten($params);
      break;
```

It is used inside a case in call method.

2023-06-07 10:46 UTC, vermakhushboo commented on src/Detector/DetectorFactory.php
> +    public function __construct(array $detectors = [])
Are you saying that the `detector.php` and `detectorFactory.php` should be moved to another folder called detector?

2023-06-07 11:10 UTC, eldadfux commented on src/VCS/Adapter.php
> +    protected function flatten(array $data, string $prefix = ''): array
OK, we can keep it.

2023-07-07 19:39 UTC, christyjacob4 commented on docker-compose.yml
> +      - /Users/khushbooverma/desktop:/usr/local/src/desktop
You can remove this

2023-07-07 19:39 UTC, christyjacob4 commented on composer.json
> +        "psr-4": {"Utopia\\VCS\\": "src/VCS", "Utopia\\Detector\\": "src/Detector"}
Let's format this JSON so each entry is on a new line

2023-07-07 19:40 UTC, christyjacob4 commented on composer.json
> +        "psr-4": {"Utopia\\Tests\\": "tests/VCS"}
similar to my comment above

2023-07-07 19:40 UTC, christyjacob4 commented on composer.json
> +        "utopia-php/cache": "^0.8.0"
what are we using the cache library for ?

2023-07-07 19:43 UTC, christyjacob4 commented on docs/add-new-adapter.md
> +To get started with implementing a new adapter, start by reviewing the [README](/README.md) to understand the goals of this library.
Lets add a few sentences on what a detector is and what needs to be done inside a detector.

2023-07-07 19:43 UTC, christyjacob4 commented on docs/add-new-adapter.md
> +{
This looks incomplete. is it intentional ?

2023-07-07 20:37 UTC, christyjacob4 commented on src/Detector/Adapter/CPP.php
> +        return ['main.cpp', 'Solution', 'CMakeLists.txt', '.clang-format'];
I think array elements are supposed to be in a new line. Please run the linter and check for the other functions as well

2023-07-07 21:00 UTC, christyjacob4 commented on src/Detector/Detector.php
> +        // 3. Look for mathch with Git language
```suggestion
        // 3. Look for match with Git language
```

2023-07-07 21:03 UTC, christyjacob4 commented on README.md
> +Although this library is part of the [Utopia Framework](https://github.com/utopia-php/framework) project, it is dependency free and can be used as standalone with any other PHP project or framework.
This library is not dependency free.. so lets remove this sentence.

2023-07-07 21:10 UTC, christyjacob4 commented on README.md
> +$installationId = '1234'; //your GitHub App Installation ID here
I don't think we should use `App::getEnv` here. It couples the usage of this library with `utopia-php/framework` . Lets keep this section generic by simply assigning these variables without the usage of `App::getEnv()`.

We should also explain what the variables mean and how to generate them

2023-07-07 21:10 UTC, christyjacob4 commented on README.md
> +You can refer to the [Contributing Guide](CONTRIBUTING.md) for more info.
@vermakhushboo have we added a link to the tutorials ?

2023-07-10 08:32 UTC, vermakhushboo commented on composer.json
> +        "utopia-php/cache": "^0.8.0"
We use it to cache temporary tokens. We don't want to regenerate them on every request. The tokens expire in every 15 minutes and are then regenerated.

2023-07-18 15:00 UTC, eldadfux requested changes

2023-07-18 15:00 UTC, eldadfux commented on CONTRIBUTING.md
> +## Adding A New Adapter
We need tutorials for both types of adapters (VCS+Detector)

2023-07-18 15:00 UTC, eldadfux commented on tests/VCS/GitHubTest.php
> +use Utopia\App;
We need tests similar to what we have in the database library. This will allow contributors to easily add a new VCS adapter.

2023-07-18 15:00 UTC, eldadfux commented on src/VCS/Adapter.php
> +    protected $headers = [];
We need to implement the interfaces of all our must have methods and describe the public API for the VCS adapters (existing and future ones). Currently this structure provide no value. It also be easier to give proper feedback on all the naming conventions and signatures used.

2023-07-19 15:27 UTC, eldadfux requested changes

2023-07-19 15:27 UTC, eldadfux commented on src/VCS/Adapter/Git.php
> +    abstract public function isGitFlow(): bool;
This is redundant, in this context it will always be true. Where do we use it? We can either move the signature one level up to `Adpater.php` and have a hardcoded implementation here that always returns true or use something like `instanceof VCS\Adapter\Git` instead in the place where we consume this method.

2023-07-19 15:27 UTC, eldadfux commented on tests/VCS/Adapter/GitHubTest.php
> +    public function setUp(): void
The implementation of all these methods can stay at the top level, I would only overwrite the setup and create a GitHub instance vs a future GitLab instance.

This way, for every future adapter we just need a new class with a unique setup, all the other methods should obey the same interface so we can trust they should work.

2023-07-19 15:27 UTC, eldadfux commented on src/VCS/Adapter/Git.php
> +    abstract public function parseWebhookEventPayload(string $event, string $payload): array;
This sounds like a private method, and one very specific to Github, I don't think it should be part of the interface.

2023-07-19 15:27 UTC, eldadfux commented on src/VCS/Adapter/Git.php
> +    abstract public function validateWebhook(string $payload, string $signature, string $signatureKey): bool;
Should this be public?

2023-07-20 11:52 UTC, vermakhushboo commented on src/VCS/Adapter/Git.php
> +    abstract public function validateWebhook(string $payload, string $signature, string $signatureKey): bool;
Yes, this method is called by the client, i.e. Appwrite in our case. So it has to be public.

2023-07-20 11:53 UTC, vermakhushboo commented on src/VCS/Adapter/Git.php
> +    abstract public function parseWebhookEventPayload(string $event, string $payload): array;
This is not a GitHub-specific method. Any VCS provider would send webhook event payload and we'd need to parse it to know which event (ex: push, pull_request) it is and perform actions accordingly.

2023-08-07 16:34 UTC, christyjacob4 commented on docker-compose.yml
> +      - WEBHOOK_SECRET
Can we document this in the readme ? 
Also can we add a section in the readme to explain what the different env variables are used for ?

2023-08-08 06:50 UTC, eldadfux requested changes
- Order of all operations needs to be organized. All operations from the same group (repository, branch, comment) have to be grouped together one after the other. Order should be consistent createX -> listX -> getX -> updateX -> deleteX
- validateWebhookEvent can be a validator, we use it only once, but instead of having a very custom and non-generic validator, I would check if we can just use existing and specific validates in Appwrite to just check for the primitive data forms we’re expecting to get and avoid the all object structure. Going lower level and keeping it simple.
- isGitFlow can be getType and we can maintain a few constants like VCS::TYPE_GIT and VCS::TYPE_SVN and return them. Makes more since than addressing each type for future support. 
- Don’t directly access array prop like `return $response['body'];` without null safety check, it should be accessed like `return $response['body'] ?? ‘’;` where the default value should be of the same type you expect. In many places it would also be wise to check for the value existence and throw an exception if not found.
- What is the result of downloadRepositoryZip downloadRepositoryTar? Is it the file contents? If yes, what happens when the file is extremely large? This could block our entire application memory and should be handled in chunks.
- If we initialize the GitHub adapter in many places anyway, I don’t see the point in using it with the dependency injection. For that, initialiseVariables can be deleted and combined with the  __construct method.
- I don’t find any usage of `generateAccessToken`, can we delete it?
- `getTotalReposCount` can be named `getRepositoriesTotalCount`, This way we keep everything consistent and when we look for a specific attribute in a response it also the last part in the method name. Our naming convention should lean to be first programatic and then human readable, in most cases both will work very well together. 
- I’m not sure what we should do with `generateCloneCommand` this is the only method that is interacting with the Git CLI instead of the API. Let’s move it to the Git adapter and add a comment to our backlog to see how we can redesign it to make sense in this context or another one.
- If we return an array, let’s use `list` as prefix. `getRepositoryLanguages` can be `listRepositoryLanguages`.
- `forkRepository` can become `createFork`.
- Can we rename `listRepositoriesForVCSApp` to `listRepositories`?

2023-08-08 06:50 UTC, eldadfux commented
Also, @vermakhushboo I think 99% of the methods you have in the GitHub adapter should also be in the abstract adapter.

2023-08-09 18:16 UTC, christyjacob4 commented on docker-compose.yml
> +      - WEBHOOK_SECRET
ping

2023-08-09 18:27 UTC, eldadfux requested changes

2023-08-09 18:27 UTC, eldadfux commented on src/VCS/Adapter/Git.php
> +    public const TYPE_GIT = 'git';
All possible types should be on the main class

2023-08-09 18:27 UTC, eldadfux commented on src/VCS/Adapter/Git/GitHub.php
> +        $command = "mkdir -p {$directory} && cd {$directory} && git config --global init.defaultBranch main && git init && git remote add origin {$cloneUrl} && git config core.sparseCheckout true &&
We might need some protection here. This could lead to a shell injection. Please talk with @Meldiron or @christyjacob4 we do something similar to protect the executor.

2023-08-09 18:38 UTC, christyjacob4 commented on src/VCS/Adapter.php
> +    abstract public function getBranchPullRequest(string $owner, string $repositoryName, string $branch): array;
```suggestion
    abstract public function getPullRequestFromBranch(string $owner, string $repositoryName, string $branch): array;
```

we already have a `getPullRequest` method , when creating new methods that are related to it, try to use the same prefix. 

And try to group them together in the file

2023-08-09 18:39 UTC, christyjacob4 commented on src/VCS/Adapter.php
> +    abstract public function getRepositoriesTotalCount(): int;
```suggestion
    abstract public function getRepositoryCount(): int;
```
Also why doesn't this function take any owner as a parameter?

2023-08-09 18:39 UTC, christyjacob4 commented on src/VCS/Adapter.php
> +    abstract public function getRepositoriesTotalCount(): int;
What repository count does it represent

2023-08-09 18:43 UTC, christyjacob4 commented on src/VCS/Adapter.php
> +     * Parses webhook event payload
the description of both these methods is the same. please check

2023-08-09 18:45 UTC, christyjacob4 commented on src/VCS/Adapter.php
> +    abstract public function getRepositoriesTotalCount(): int;
lets also group all the repository related functions together in the file, similarly for the pull request related functions etc. Lets have a logical structure in the file

2023-08-09 18:46 UTC, christyjacob4 requested changes
Another general comment that we can tackle in the next version is 

- initialiseVariables should be like a factory static method called GitHub::initialise() or GitHub::init()

2023-08-09 18:46 UTC, vermakhushboo commented on src/VCS/Adapter.php
> +    abstract public function getRepositoriesTotalCount(): int;
We don't use it in Appwrite any longer. So removing it.

2023-08-09 19:06 UTC, vermakhushboo commented on src/VCS/Adapter/Git/GitHub.php
> +        $command = "mkdir -p {$directory} && cd {$directory} && git config --global init.defaultBranch main && git init && git remote add origin {$cloneUrl} && git config core.sparseCheckout true &&
Discussed with Christy. We'll handle it on Appwrite repository by validating the parameters and mounting the /tmp directory to a named volume.

2023-08-09 19:46 UTC, eldadfux commented on src/VCS/Adapter.php
> +    abstract public function getRepositoriesTotalCount(): int;
@christyjacob4 this is fine, it represent the attribute name which is `total_count`

2023-08-09 20:11 UTC, vermakhushboo commented on src/VCS/Adapter/Git/GitHub.php
> +        $command = "mkdir -p {$directory} && cd {$directory} && git config --global init.defaultBranch main && git init && git remote add origin {$cloneUrl} && git config core.sparseCheckout true &&
Added `escapeshellarg` to params.

2023-08-09 20:34 UTC, christyjacob4 approved these changes

2023-08-09 20:48 UTC, merged